services:
  # 1. Base de Datos (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: churn_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME} # Lee del .env
      POSTGRES_USER: ${DB_USER} # Lee del .env
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Lee del .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - churn_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Data Science (FastAPI - Python)
  ai-service:
    build:
      context: ./data-science
      dockerfile: Dockerfile
    container_name: churn_ai_service
    restart: unless-stopped
    ports:
      - "${AI_PORT}:8000"
    volumes:
      - ./data-science:/app
    networks:
      - churn_network

  # 3. Backend (Spring Boot - Java)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: churn_backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - AI_SERVICE_URL=http://ai-service:8000/
    volumes:
      - ./backend:/app
      - /app/target
    depends_on:
      db:
        condition: service_healthy
      ai-service:
        condition: service_started
    networks:
      - churn_network

  # 4. Frontend (Vue.js - Modo Desarrollo)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: churn_frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:5173"
    environment:
      - VITE_API_URL=http://localhost:${BACKEND_PORT}/api/v1
    volumes:
      - ./frontend:/app # Sincroniza tu código
      - /app/node_modules # Volumen anónimo (Mantiene los módulos de Linux aislados)
    networks:
      - churn_network
    # CAMBIO AQUÍ: Usamos pnpm
    command: ["pnpm", "run", "dev", "--host"]
    
volumes:
  postgres_data:
    driver: local

networks:
  churn_network:
    driver: bridge
